package assignment.command;

public enum CommandType {
	LOGIN_COMMAND, 
	ADD_ARTICLE,
	GET_ALL_ARTICLE_COMMAND,
	CREATE_USER_COMMAND,
	USER_PROFILE_COMMAND,
	SHOW_ALL_USERS_COMMAND,
	BAN_USER_COMMAND;
}
